noun = ['Mountain', 'Ocean', 'Building', 'Playground', 'Animal']
adjectives = ['Running', 'Walking', 'Cycling', 'Sleeping', 'Eating']
people = ['Mother', 'Father', 'Sister', 'Brother', 'Friend', 'Husband']
places = ['Farm', 'Beach', 'Work', 'School', 'City']
weather = ['Sunny', 'Raining', 'Sleat', 'Windy', 'Snow', 'Stormy']
animals = ['Dog', 'Cat', 'Goldfish', 'Hamster']
birds = ['Robin', 'Blackbird', 'Crow', 'Goldfinch']
proverb = ["Every cloud has a silver lining", "No news is good news"]